return {
  'ellisonleao/gruvbox.nvim',
  priority = 1000,
  config = true,
  opts = {
    terminal_colors = true,
    undercurl = true,
    underline = true,
    bold = true,
    italic = {
      strings = true,
      emphasis = true,
      comments = true,
      operators = false,
      folds = true,
    },
    strikethrough = true,
    invert_selection = false,
    invert_signs = false,
    invert_tabline = false,
    inverse = true,
    contrast = 'hard',
    palette_overrides = {},
    dim_inactive = false,
    overrides = {
      Normal = { bg = '#0D1117' },
      LspReferenceText = { bg = '#3c4048' },
      LspReferenceRead = { bg = '#3c4048' },
      LspReferenceWrite = { bg = '#4a3a2a' },
      MatchParen = { bg = '#3c4048', bold = true },
    },
    transparent_mode = true,
  },
}
